server:
  port: 8002

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:  #手动配置路由,查看路由信息：http://127.0.0.1:8002/actuator/gateway/routes
#      discovery:
#        locator:
#          enabled: true #默认为 false，开启通过服务中心的自动根据 serviceId 创建路由的功能。
#          # 服务名小写
#          lower-case-service-id: true
#      routes:
#        - id: business-service
#          # lb代表从注册中心获取服务，且已负载均衡方式转发，loadbalance缩写
#          uri: lb://business-service
#          predicates:
#            - Path=/business/**
#          # 加上StripPrefix=1，否则转发到后端服务时会带上business前缀
#          filters:
#            # 进行token过滤
#            #- TokenAuthenticationFilter
#            - StripPrefix=1

# 注册中心
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    instance:
      prefer-ip-address: true
      instance-id: gateway-service:127.0.0.1:8002


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
